srcode/user/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, SubmitField, BooleanField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length, Email, ValidationError
from flask import request
from srcode.models import User
from flask_babel import lazy_gettext as _i  #Translating function for i8n and l6n support
#from wtforms.fields.html5 import DateField. Used for dates uses a yy-mm-dd forms


class UpdateAdminAccountForm(FlaskForm):
    email = StringField(_i('Email'), validators=[DataRequired(), Email()])
    username = StringField('Username', validators = [DataRequired(), Length(min=1, max=20, message = 'Username must be between 2 and 20 characters')])
    confirmed = BooleanField('Confirmed')
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'jpeg','png'])])
    role = SelectField('Role', coerce=int, choices = [(1, 'admin'), (0,'user')])
    bio = StringField('About me', validators = [DataRequired(), Length(min=1, max=100, message ='Must be below 100 characters')])
    submit = SubmitField('Submit')


class UpdateAccountForm(FlaskForm):
     username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
     email = StringField('Email',
                        validators=[DataRequired(), Email()])
     bio = StringField('About me',
                           validators=[DataRequired(), Length(min=1, max=120)])
     picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'jpeg','png'])])
     submit = SubmitField('Update')

     def validate_username(self, username):
          if username.data != current_user.username:
               user = User.query.filter_by(username=username.data).first()
               if user:
                    raise ValidationError('That username is taken. Please choose a different one.')

     def validate_email(self, email):
          if email.data != current_user.email:
               user = User.query.filter_by(email=email.data).first()
               if user:
                    raise ValidationError('That email is taken. Please choose a different one.')


class PostForm(FlaskForm):
    tag = StringField('Any Post Tags?')
    content = TextAreaField('Content', validators=[DataRequired()])
    post_image = FileField('Update Post Picture?', validators=[FileAllowed(['jpg','gif','jpeg','png'])])
    submit = SubmitField('Post')
class CommentForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Your comment', validators=[DataRequired()])
    submit = SubmitField('Post Comment')

class SearchForm(FlaskForm):
    '''Query is a prefix for standard search engines'''
    q = StringField(_i('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

class follow_unfollowForm(FlaskForm):
    '''Implemented as a form to protect against CSRF attacks'''
    submit = SubmitField('Submit')
    
class MessageForm(FlaskForm):
    message = TextAreaField(_i('Message*'), validators=[DataRequired(), Length(min=0, max=140)])
    submit = SubmitField(_i('Send'))

srcode/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from srcode.user import routes

srcode/user/routes.py
from ..auth.decorator import admin_required
from ..essearch import add_to_index
from sqlalchemy import func
from flask import render_template, url_for, flash, redirect, request, abort, jsonify, g
from srcode import cache, db
from .forms import MessageForm, UpdateAccountForm, PostForm, CommentForm, follow_unfollowForm, UpdateAdminAccountForm, SearchForm
from twilio.jwt.access_token import AccessToken
from twilio.jwt.access_token.grants import VideoGrant
from ..models import Message, Notification, SavedPosts, User, Post, Role, PostLike, Comment
from .email import send_post_notification_email
from flask_login import current_user, login_required
import requests
from datetime import datetime
from ..user import bp
from config import Config
from flask_babel import _
from guess_language import guess_language
from ..uploads3 import save_picture
from .decorator import check_confirmed
from flask_babel import _, get_locale


@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm() 
        g.user_followers = get_following(current_user.username) 
        #g.current_user_messages = view_messages() 
    g.locale = str(get_locale())  

@bp.route('/')
@bp.route("/home")
@login_required
#@check_confirmed
def home():
    posts = current_user.followed_posts()
    return render_template('main/home.html', title='Home', posts=posts)
  

@bp.route("/about")
#@login_required
#@check_confirmed
@cache.cached(timeout=50)
def about():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('main/about.html',  posts=posts, title='All posts')  

@bp.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('user.home'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page, 5)
    next_url = url_for('user.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * 5 else None
    prev_url = url_for('user.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('main/search.html', title=_('Search'), posts=posts,
                           next_url=next_url, total = total, prev_url=prev_url)  
    
@bp.route('/trending', methods = ['GET', 'POST'])
@cache.cached(timeout=50, key_prefix = 'trending_posts')
def get_trending():
    posts = db.session.query(Post).outerjoin(PostLike).group_by(Post.id).order_by(func.count().desc()).all() 
    #posts = Post.query.order_by(Post.likes.desc())
    return render_template('main/trending.html', posts = posts)

@bp.route('/<username>', methods=['GET'])
@login_required
def user_profile(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    form = UpdateAccountForm()
    form.username.data = user.username
    form.email.data = user.email
    form.about_me = user.bio   
    user_followers,user_following = set(user.followers), len(set(user.followed))
    no_followers =  len(user_followers)
    current_user_following = set(current_user.followed)
    exist_intersection = current_user_following.intersection(user_followers)
    no_exist_intersection = len(exist_intersection)
    exist_follows = current_user_following.isdisjoint(user_followers)
    image_file = f'https://{Config.AWS_BUCKET}.s3.amazonaws.com/profile_pics/Profile_pics/'+ str(user.image_file)
    return render_template('user/user.html', title='Your Account',
                           image_file=image_file, exist_follows=exist_follows, exist_intersection=exist_intersection, user_followers=user_followers, user_following=user_following, no_exist_intersection=no_exist_intersection, no_followers=no_followers, form=form,post=post, posts=posts, user=user)

@bp.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if request.method == "POST":
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = save_picture(form.picture.data, 'profile')
                current_user.image_file = picture_file
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.bio = form.bio.data
            db.session.commit()
            flash(f'Your account has been updated, {current_user.username}!', 'success')
            return redirect(url_for('user.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
    image_file = f'https://{Config.AWS_BUCKET}.s3.amazonaws.com/profile_pics/Profile_pics/'+ str(current_user.image_file)
    current_user_messages = current_user.messages_received.order_by(
        Message.date_read.desc())
    return render_template('user/account.html', title='Account',
                           image_file=image_file, current_user_messages=current_user_messages, form=form)
@bp.route('/notifications')
@login_required
def get_notifications():
    last_notifications = request.args.get('since',0.0, type=float)
    user_notifications = current_user.notifications.filter(
    Notification.timestamp > last_notifications).order_by(Notification.timestamp.asc())
    return jsonify([{
    'name' : notif.name,
    'data' : notif.get_json(),
    'timestamp' : notif.timestamp 
    } for notif in user_notifications])
        
@bp.route('/edit_admin_profile/<int:id>', methods=['GET', 'POST'])
@admin_required
@login_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = UpdateAdminAccountForm(user=user)
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_profile = picture_file
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.bio = form.bio.data
        db.session.add(user)
        flash('Your profile is updated!', 'success')
        return redirect(request.referrer)
    form.email.data = user.email
    form.username.data = user.username
    form.bio = user.bio
    form.role.data = user.role_id
    form.confirmed.data = user.confirmed
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('user/edit_admin_profile.html', image_file=image_file, form=form, user=user)

@bp.route("/<string:username>/post/new", methods=['GET', 'POST'])
@login_required
#@check_confirmed
def new_post(username):
    ''' Creates a new post'''
    user = User.query.filter_by(username=username).first_or_404()
    form = PostForm()
    if request.method == 'POST':
        if form.validate_on_submit() and form.post_image.data: 
            #post_photo = url_for('static', filename='profile_pics/' + post_file)   
            #post_photo = current_user.posts.post_image
            post_language = guess_language(form.content.data)
            if post_language == 'UNKNOWN' or len(post_language) > 7:
                post_language = ''
            
            post_file = save_picture(form.post_image.data, 'post')
            if not isinstance(post_file, list):
                post = Post(tag=form.tag.data, content=form.content.data, author=current_user, post_image =post_file, language = post_language)
                db.session.add(post)
                db.session.commit()
            for image in post_file:
                post = Post(tag=form.tag.data, content=form.content.data, author=current_user, post_image =image, language = post_language)
                db.session.add(post)
            db.session.commit()    
            flash(f'{current_user.username}, your post has been created!', 'success')
            '''send a notification email to each of the user's followers'''
            send_post_notification_email(user.followers, post=post, user=user, date_posted = post.date_posted.strftime('%a,%B,%H, %p'))
            return redirect(url_for('user.home'))
            
          
    #post_photo = url_for('static', filename='post_pics/' + save_picture(form.post_image.data, 'post'))   
    return render_template('user/create_posts.html', title='New Post', 
                           form=form, legend='New Post')

@bp.route("/post/<int:post_id>")
#@check_confirmed
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('main/posts.html', post=post)
    

@bp.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
#@check_confirmed
def update_post(post_id):
    ''' takes in a specific user_id(attached to the current user), and updates the post belonging to them''' 
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:  #Only current logged in user should be able to post
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.tag = form.tag.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('user.post', post_id=post.id))
    elif request.method == 'GET':
        form.tag.data = post.tag
        form.content.data = post.content
    return render_template('user/create_posts.html', title='Update Post',
                           form=form, legend='Update Post')


@bp.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
@check_confirmed
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:

srcode/templates/user/_refactor_account_forms.html
{% macro render_account_forms(field, form) %}
<div class="form-group">
     {{ field.label(class="form-control-label") }}
    {% if form == picture %}
          {{ form.picture(class="form-control-file") }}
     {% endif %}
     {% if field.errors %}
          {{ field(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
               {% for error in field.errors %}
                    <span>{{ error }}</span>
               {% endfor %}
          </div>
     {% else %}
          {% if form == bio %}
               <p class = "text-secondary"> {{ form.bio(class='form-control form-control-sm') }} 
          {% else%}
          {{ field(class="form-control form-control-lg") }}
          {% endif %}
     {% endif %}
</div> 
{% endmacro %}

srcode/templates/user/export_posts.html
<p> Dear {{ user.username}}</p>
<p>Please find attached the archive of your posts that you requested.</p>
<p>Sincerely,</p>
<p>The Flaskgram Team</p>

srcode/templates/user/following.html
{% extends "layout3.html" %}
{% block content %}
          {% for followed in selected_user_following %}
               <div class="content-section">
               <div class="media">
               <div class="media-body"> 
               <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + followed.image_file) }}">
               <a class="mr-2" href="{{ url_for('user.user_profile', username=followed.username) }}">{{ followed.username }}
               </a>
               {% if not current_user.is_following(followed) and current_user != selected_user %}
           
               
                {% endif %}
     
               </div>
               </div>
          </div>
          {% endfor %}   
{% endblock content%}

srcode/templates/user/notifications.html
{% extends 'layout3.html'%}

{% block content %}

               
              
   {%if current_user == user %}
   <h1> Notifications</h1>
          {{ user_notifications }}
   {% endif %}

{% endblock content %}

srcode/templates/user/post_notifications.html
<p>Hey {{ user.username }}!</p>
<p>
   One of the people you follow has created a new post {{ date_posted }}!

</p>
<p>Check it it out below!</p>
<p>{{ url_for('user.post', post_id =post.id, _external=True) }}</p>

<p>Sincerely,</p>
<p>The Microblog Team</p>

srcode/templates/user/savedposts.html
{%extends 'layout3.html' %}
{% block content %}
<br>
{% for savedpost in user_saved_posts %}
<br>
<div class="card w-85">
  <div><img class="rounded-circle article-img" src="https://flaskium.s3.amazonaws.com/profile_pics/Profile_pics/{{ savedpost.user.image_file }}">
  <a class="mr-2" href="{{ url_for('user.user_profile', username=savedpost.user.username) }}">{{ savedpost.user.username }}</a> <small class="text-muted">{{ moment(savedpost.saved.date_posted).fromNow()}}</small> 
  <button type="button" class="btn btn-success-outline btn-sm m-1 float-right" data-toggle="modal"
  data-target="#deleteModal">...</button>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
  <div class="modal-header">
    
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-secondary" data-dismiss="modal">Back</button>
<a href="{{ url_for('user.post', post_id = savedpost.saved.id) }}" class="btn btn-secondary"> Go to post?</a>
{%if current_user.receive_notifs%} <a class="btn btn-info" href="{{ url_for('user.post_notifs', username=savedpost.user.username,action='no') }}">Unsubscribe me!</a> {% else %} <a class="btn btn-success" href="{{ url_for('user.post_notifs', username=savedpost.user.username, action = 'yes') }} ">Subscribe me!</a>  {% endif %}
{{ share.create(title='Share the post?')}}
</div>

  </div>
</div>
</div>
</div>
  <img class="card-img-top" src="https://flaskium.s3.amazonaws.com/profile_pics/Post/{{ savedpost.saved.post_image}}" alt="post-image">
 
  <small class="text-muted">{{ savedpost.saved.date_posted.strftime('%d, %B, %Y') }}</small>
  <div class="card-body">
    <p class="card-text">{{ savedpost.saved.content }}</p>
    <small class="card-text">  {{ savedpost.saved.tag }}</small>
  </div>
  {% if savedpost.saved.language and savedpost.saved.language != g.locale %}
    <a href="#">{{ _('Translate') }}</a>
  {% endif %}
  <div>
    {% if selected_user != current_user %}
      {% if current_user.is_authenticated %}
      <div class='float-right'>
        {% if current_user.has_saved_post(savedpost.saved) %}
        <a href="{{ url_for('user.bookmark', post_id=post.id, action = 'save') }}">
        <img src="https://img.icons8.com/ios/35/000000/bookmark-ribbon.png"/></a>
        {% else %}
        <a href="{{ url_for('user.bookmark', post_id=post.id, action = 'unsave') }}">
        <img src="https://img.icons8.com/material-rounded/24/000000/bookmark-ribbon.png"/></a>
        {% endif %}
      </div>
        {% if current_user.has_liked_post(savedpost.saved) %}
          <a class="btn btn-info btn-sm mt-1 mb-1"
          href="{{ url_for('user.like_action', post_id=post.id, action='unlike')}}"> <i onclick="myFunction(this)" class="fa fa-thumbs-down"></i>
          <span class="badge"> {{ savedpost.saved.likes.count()  }}</span></a>
          
        {% else %}
              <a class="btn btn-success btn-sm mt-1 mb-1"
                href="{{ url_for('user.like_action', post_id=savedpost.saved.id, action='like') }}"><i onclick="myFunction(this)" class="fa fa-thumbs-up"></i> <span class="badge"> {{ savedpost.saved.likes.count() }}</span>
               </a>
             
        {% endif %}
    {% endif %}
    <a class="btn btn-sm mt-1 mb-1 btn-primary" data-toggle="collapse" href="#collapseExample" role="button"
    aria-expanded="false" aria-controls="collapseExample">
    Comment?
  </a>

  <button class="btn btn-sm mt-1 mb-1 btn-primary" id="stripeButton"> Tip the author?</button>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <p>When commenting please adhere to the community guidelines!
      </p>
      <a class="btn btn-success btn-sm mt-1 mb-1" href="{{ url_for('user.create_comment', post_id=savedpost.saved.id) }}">Comment
      </a>
    </div>
  </div>

  {% else %}
  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('user.update_post', post_id=savedpost.saved.id) }}">Update</a>
  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
    data-target="#deleteModal">Delete</button>

{% endif %}
    
  </div>

</div>
{%endfor %}
{% endblock content %}

srcode/templates/user/user.html
{% extends "layout3.html" %}
{% block content %}
<title> {{user.username }} account </title>
<div class="content-section">
     <div class="media">
       <img class="rounded-circle account-img" src="{{ image_file }}">
       <div class="media-body">
              <div>
               <h2 class="account-heading">{{ _(user.username) }}</h2> 😆
               {% if user.is_following(current_user) and current_user != user%}
               <span class="badge badge-secondary">Follows you</span>
               {% endif %}
               </div>

               
               <p class= "text-secondary"> Last seen {{ moment(user.last_seen).fromNow()}}
               <p class='text-secondary'> Joined {{ moment(user.registered_on).fromNow() }}</p>
               <p class = "text-secondary">  {{ _(user.bio) }}</p>
               <div><a href ="{{url_for('user.all_followers', username=user.username)}}" class="btn btn-outline danger">{{ no_followers }} followers</a> <a class= "btn btn-outline danger"href="{{url_for('user.get_following', username=user.username)}}">{{ user_following }} following </a> <a href ="#" class='text-secondary'> {{ posts.total }} posts </a> </div>
               
        <div>
        <div>
          {% if not exist_follows and user!= current_user %}   
          <a class="btn-outline danger" href="{{ url_for('user.all_followers', username=user.username) }}">
            Followed by 
            {% for user_follower in exist_intersection  %}
            <strong>{{ user_follower.username }},</strong>
            {% endfor %}
                {% if no_exist_intersection > 3%}
                    and  {{ no_exist_intersection - 3 }} more
                {% endif %}
          {% elif exist_follows and user != current_user %}
           Not followed by anyone you follow
            {% endif %}
          </p>
        </div>
        
            {% if current_user.is_authenticated %}
                {% if user == current_user and current_user.confirmed %}
                   
                    <a class= 'btn btn-success btn-sm mt-1 mb-1' href="{{ url_for('user.user_posts', username=user.username)}}"> Check out your other posts</a>     
                {% elif not current_user.confirmed and user == current_user %}
                  <a class= 'btn btn-danger btn-sm mt-1 mb-1' href="{{ url_for('auth.unconfirmed')}}"> Please confirm your account</a>   
                {% endif %}
            {% if current_user.is_following(user) and current_user != user  %}
            <button type="button" class="btn btn-success btn-sm m-1" data-toggle="modal"
            data-target="#deleteModal">Following</button>
            <a href="{{url_for('user.videochat') }}" class="btn btn-success btn-sm mt-1 mb-1">
              Video Chat?
            </a>
            <a href="{{url_for('user.send_message', recepient=user.username) }}" class="btn btn-success btn-sm mt-1 mb-1">
              Message
            </a>
            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Unfollow? {{user.username}} </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('user.follow_action', username=user.username, action = 'unfollow') }}" method="POST">{{ form.hidden_tag() }}{{ form.submit(class='btn btn-success')}}
          </form>     
              </div>
            </div>
          </div>
          </div>
            {% elif not current_user.is_following(user) and current_user != user %}
            <p>
                <form action="{{ url_for('user.follow_action', username=user.username, action='follow') }}" method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.submit(class = 'btn btn-outline-info', value='follow') }}
                </form>   
            </p>
            <a class= 'btn btn-success btn-sm mt-1 mb-1' href="{{ url_for('user.user_posts', username=user.username)}}"> Check out this user's posts</a>
            
               
            {% endif %}
        </div>

         <div>
        {% endif %} 
        {% if user == current_user and current_user.admin %}
           <a class ='btn btn-info btn-sm mt-1 mb-1'href="{{ url_for('user.edit_profile_admin', id = user.id)  }}"> Edit Your Profile</a>
        {% elif current_user == user and not current_user.admin %}
          <p><a class = "btn btn-success btn-sm mt-1 mb-1" href="{{ url_for('user.account') }}">Edit your profile</a></p>
        {% endif %}
         
         </div>
      <div>
        <img class="rounded-circle account-img" src="https://images.unsplash.com/photo-1588165231518-b4b22bfa0ddf?ixlib=rb-1.2.1&auto=format&fit=crop&w=2134&q=80">
        <h2> Outfits 💪</h2> 
        <img class="rounded-circle account-img" src="https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2134&q=80">
        <h2> Food 🍗</h2>
       
      </div>
     </div>
    </div>
  </div>
     <div>
     <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">{{user.username}} Posts</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="https://flaskium.s3.amazonaws.com/profile_pics/Profile_pics/{{ post.author.image_file }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('user.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ moment(post.date_posted).fromNow() }}</small>
            </div>
            <div>
            <img src="https://flaskium.s3.amazonaws.com/profile_pics/Post/{{ post.post_image}}" alt="{{post.author.username }}-image">
            <h2><a class="article-title" href="{{ url_for('user.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </div>
        </article>
    {% endfor %}
      </div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        {% if not current_user.get_specific_task_in_progress('export_posts') %}
                <p>
                  <a class= 'btn btn-success btn-sm mt-1 mb-1' href="{{ url_for('user.export_users_posts')}}"> Export your posts.</a>
            
                </p>
        {% endif %}
      </div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <a href="mailto:{{ user.email }}"> Email </a>


      </div>
    </div>
     </div>






{% endblock content%}

srcode/templates/user/user_posts.html
{% extends "layout3.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('user.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('user.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('user.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('user.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}